# Names are same as PipelineStep
preprocess:
    sample_size: 1

feature_engineer:
    some_int_parameter: 1

select_features:
    some_int_parameter: 1

split_dataset:
    test_size: 0.2

train:
    skip_cv: True
    n_splits: 4
    train_final_model: True
